"""empty message

Revision ID: 2bf1eb2faa9b
Revises: 67bbcb6debc9
Create Date: 2026-06-04 15:31:23.275975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf1eb2faa9b'
down_revision: Union[str, Sequence[str], None] = '67bbcb6debc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Guilds', sa.Column('welcome_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Guilds', 'welcome_message')
    # ### end Alembic commands ###
