"""empty message

Revision ID: 41b124431afa
Revises: f68e29a1cc06
Create Date: 2026-04-03 22:29:07.474126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b124431afa'
down_revision: Union[str, Sequence[str], None] = 'f68e29a1cc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Owners', sa.Column('access_token', sa.String(length=512), nullable=True))
    op.add_column('Owners', sa.Column('session_token', sa.String(length=512), nullable=True))
    op.add_column('Owners', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'Owners', ['session_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Owners', type_='unique')
    op.drop_column('Owners', 'expires_at')
    op.drop_column('Owners', 'session_token')
    op.drop_column('Owners', 'access_token')
    # ### end Alembic commands ###
