"""empty message

Revision ID: 4e107ce2a31c
Revises: 58ad868c1be7
Create Date: 2026-05-27 23:32:18.970616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e107ce2a31c'
down_revision: Union[str, Sequence[str], None] = '58ad868c1be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Owners_session_token_key'), 'Owners', type_='unique')
    op.drop_column('Owners', 'session_token')
    op.drop_column('Owners', 'refresh_token')
    op.drop_column('Owners', 'access_token')
    op.drop_column('Owners', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Owners', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Owners', sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('Owners', sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('Owners', sa.Column('session_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('Owners_session_token_key'), 'Owners', ['session_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
