"""empty message

Revision ID: 58ad868c1be7
Revises: c883dc643447
Create Date: 2026-05-25 21:08:40.013151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ad868c1be7'
down_revision: Union[str, Sequence[str], None] = 'c883dc643447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Guilds', 'config_json')
    op.add_column('Users', sa.Column('warnings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'warnings')
    op.add_column('Guilds', sa.Column('config_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
