"""empty message

Revision ID: 67bbcb6debc9
Revises: 9695cba44439
Create Date: 2026-05-29 12:08:07.285917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67bbcb6debc9'
down_revision: Union[str, Sequence[str], None] = '9695cba44439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subscriptions')
    op.drop_table('Payments')
    op.drop_table('SubscriptionPlans')
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], name=op.f('Subscriptions_guild_id_fkey')),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.id'], name=op.f('Subscriptions_payment_id_fkey')),
    sa.ForeignKeyConstraint(['plan_id'], ['SubscriptionPlans.id'], name=op.f('Subscriptions_plan_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['Owners.ds_id'], name=op.f('Subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Subscriptions_pkey'))
    )
    op.create_table('SubscriptionPlans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_yearly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('SubscriptionPlans_pkey'))
    )
    op.create_table('Payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['SubscriptionPlans.id'], name=op.f('Payments_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Payments_pkey')),
    sa.UniqueConstraint('payment_id', name=op.f('Payments_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
