"""init

Revision ID: c883dc643447
Revises: 
Create Date: 2026-05-21 17:54:44.404253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c883dc643447'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Owners',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ds_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('session_token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ds_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('SubscriptionPlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('icon_hash', sa.String(length=256), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Owners.ds_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=256), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['SubscriptionPlans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('DisabledCommands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('command_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['SubscriptionPlans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Owners.ds_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['Guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['Messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Attachments')
    op.drop_table('Messages')
    op.drop_table('Log_entries')
    op.drop_table('Users')
    op.drop_table('Subscriptions')
    op.drop_table('DisabledCommands')
    op.drop_table('Payments')
    op.drop_table('Guilds')
    op.drop_table('SubscriptionPlans')
    op.drop_table('Owners')
    # ### end Alembic commands ###
