"""empty message

Revision ID: ec083061b5c4
Revises: 2bf1eb2faa9b
Create Date: 2026-06-13 16:00:35.976651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec083061b5c4'
down_revision: Union[str, Sequence[str], None] = '2bf1eb2faa9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'message_count')
    op.drop_column('Users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('message_count', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
