"""empty message

Revision ID: f68e29a1cc06
Revises: 83b5312aa548
Create Date: 2026-03-29 22:53:01.841038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68e29a1cc06'
down_revision: Union[str, Sequence[str], None] = '83b5312aa548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Owners', sa.Column('refresh_token', sa.String(length=512), nullable=True))
    op.alter_column('Owners', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Owners', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('Owners', 'refresh_token')
    # ### end Alembic commands ###
