"""empty message

Revision ID: fb56ea85e626
Revises: 5e53b1dfaecf
Create Date: 2026-03-17 12:06:20.084516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb56ea85e626'
down_revision: Union[str, Sequence[str], None] = '5e53b1dfaecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Guilds', 'Owners', ['owner_id'], ['ds_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Guilds', type_='foreignkey')
    # ### end Alembic commands ###
