FROM python:3.13.9-slim

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*


RUN pip install uv && \
    uv --version

WORKDIR /app

COPY pyproject.toml uv.lock* ./

RUN uv sync

COPY .. .

EXPOSE 8000