name: Build Backend Service


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Download repo
        uses: actions/checkout@v4
          with:
            path: ./home/DiscordCursBot

      - name: Copy .env backend file
        run: |
          echo "coping .env"

      - name: Run Backend
        run: |
          make build
      